# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: prometheus_metrics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18prometheus_metrics.proto\x12\x14io.prometheus.client\"(\n\tLabelPair\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x16\n\x05Gauge\x12\r\n\x05value\x18\x01 \x01(\x01\"\x18\n\x07\x43ounter\x12\r\n\x05value\x18\x01 \x01(\x01\"+\n\x08Quantile\x12\x10\n\x08quantile\x18\x01 \x01(\x01\x12\r\n\x05value\x18\x02 \x01(\x01\"e\n\x07Summary\x12\x14\n\x0csample_count\x18\x01 \x01(\x04\x12\x12\n\nsample_sum\x18\x02 \x01(\x01\x12\x30\n\x08quantile\x18\x03 \x03(\x0b\x32\x1e.io.prometheus.client.Quantile\"\x18\n\x07Untyped\x12\r\n\x05value\x18\x01 \x01(\x01\"c\n\tHistogram\x12\x14\n\x0csample_count\x18\x01 \x01(\x04\x12\x12\n\nsample_sum\x18\x02 \x01(\x01\x12,\n\x06\x62ucket\x18\x03 \x03(\x0b\x32\x1c.io.prometheus.client.Bucket\"7\n\x06\x42ucket\x12\x18\n\x10\x63umulative_count\x18\x01 \x01(\x04\x12\x13\n\x0bupper_bound\x18\x02 \x01(\x01\"\xbe\x02\n\x06Metric\x12.\n\x05label\x18\x01 \x03(\x0b\x32\x1f.io.prometheus.client.LabelPair\x12*\n\x05gauge\x18\x02 \x01(\x0b\x32\x1b.io.prometheus.client.Gauge\x12.\n\x07\x63ounter\x18\x03 \x01(\x0b\x32\x1d.io.prometheus.client.Counter\x12.\n\x07summary\x18\x04 \x01(\x0b\x32\x1d.io.prometheus.client.Summary\x12.\n\x07untyped\x18\x05 \x01(\x0b\x32\x1d.io.prometheus.client.Untyped\x12\x32\n\thistogram\x18\x07 \x01(\x0b\x32\x1f.io.prometheus.client.Histogram\x12\x14\n\x0ctimestamp_ms\x18\x06 \x01(\x03\"\x88\x01\n\x0cMetricFamily\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04help\x18\x02 \x01(\t\x12.\n\x04type\x18\x03 \x01(\x0e\x32 .io.prometheus.client.MetricType\x12,\n\x06metric\x18\x04 \x03(\x0b\x32\x1c.io.prometheus.client.Metric*M\n\nMetricType\x12\x0b\n\x07\x43OUNTER\x10\x00\x12\t\n\x05GAUGE\x10\x01\x12\x0b\n\x07SUMMARY\x10\x02\x12\x0b\n\x07UNTYPED\x10\x03\x12\r\n\tHISTOGRAM\x10\x04\x42\x16\n\x14io.prometheus.client')

_METRICTYPE = DESCRIPTOR.enum_types_by_name['MetricType']
MetricType = enum_type_wrapper.EnumTypeWrapper(_METRICTYPE)
COUNTER = 0
GAUGE = 1
SUMMARY = 2
UNTYPED = 3
HISTOGRAM = 4


_LABELPAIR = DESCRIPTOR.message_types_by_name['LabelPair']
_GAUGE = DESCRIPTOR.message_types_by_name['Gauge']
_COUNTER = DESCRIPTOR.message_types_by_name['Counter']
_QUANTILE = DESCRIPTOR.message_types_by_name['Quantile']
_SUMMARY = DESCRIPTOR.message_types_by_name['Summary']
_UNTYPED = DESCRIPTOR.message_types_by_name['Untyped']
_HISTOGRAM = DESCRIPTOR.message_types_by_name['Histogram']
_BUCKET = DESCRIPTOR.message_types_by_name['Bucket']
_METRIC = DESCRIPTOR.message_types_by_name['Metric']
_METRICFAMILY = DESCRIPTOR.message_types_by_name['MetricFamily']
LabelPair = _reflection.GeneratedProtocolMessageType('LabelPair', (_message.Message,), {
  'DESCRIPTOR' : _LABELPAIR,
  '__module__' : 'prometheus_metrics_pb2'
  # @@protoc_insertion_point(class_scope:io.prometheus.client.LabelPair)
  })
_sym_db.RegisterMessage(LabelPair)

Gauge = _reflection.GeneratedProtocolMessageType('Gauge', (_message.Message,), {
  'DESCRIPTOR' : _GAUGE,
  '__module__' : 'prometheus_metrics_pb2'
  # @@protoc_insertion_point(class_scope:io.prometheus.client.Gauge)
  })
_sym_db.RegisterMessage(Gauge)

Counter = _reflection.GeneratedProtocolMessageType('Counter', (_message.Message,), {
  'DESCRIPTOR' : _COUNTER,
  '__module__' : 'prometheus_metrics_pb2'
  # @@protoc_insertion_point(class_scope:io.prometheus.client.Counter)
  })
_sym_db.RegisterMessage(Counter)

Quantile = _reflection.GeneratedProtocolMessageType('Quantile', (_message.Message,), {
  'DESCRIPTOR' : _QUANTILE,
  '__module__' : 'prometheus_metrics_pb2'
  # @@protoc_insertion_point(class_scope:io.prometheus.client.Quantile)
  })
_sym_db.RegisterMessage(Quantile)

Summary = _reflection.GeneratedProtocolMessageType('Summary', (_message.Message,), {
  'DESCRIPTOR' : _SUMMARY,
  '__module__' : 'prometheus_metrics_pb2'
  # @@protoc_insertion_point(class_scope:io.prometheus.client.Summary)
  })
_sym_db.RegisterMessage(Summary)

Untyped = _reflection.GeneratedProtocolMessageType('Untyped', (_message.Message,), {
  'DESCRIPTOR' : _UNTYPED,
  '__module__' : 'prometheus_metrics_pb2'
  # @@protoc_insertion_point(class_scope:io.prometheus.client.Untyped)
  })
_sym_db.RegisterMessage(Untyped)

Histogram = _reflection.GeneratedProtocolMessageType('Histogram', (_message.Message,), {
  'DESCRIPTOR' : _HISTOGRAM,
  '__module__' : 'prometheus_metrics_pb2'
  # @@protoc_insertion_point(class_scope:io.prometheus.client.Histogram)
  })
_sym_db.RegisterMessage(Histogram)

Bucket = _reflection.GeneratedProtocolMessageType('Bucket', (_message.Message,), {
  'DESCRIPTOR' : _BUCKET,
  '__module__' : 'prometheus_metrics_pb2'
  # @@protoc_insertion_point(class_scope:io.prometheus.client.Bucket)
  })
_sym_db.RegisterMessage(Bucket)

Metric = _reflection.GeneratedProtocolMessageType('Metric', (_message.Message,), {
  'DESCRIPTOR' : _METRIC,
  '__module__' : 'prometheus_metrics_pb2'
  # @@protoc_insertion_point(class_scope:io.prometheus.client.Metric)
  })
_sym_db.RegisterMessage(Metric)

MetricFamily = _reflection.GeneratedProtocolMessageType('MetricFamily', (_message.Message,), {
  'DESCRIPTOR' : _METRICFAMILY,
  '__module__' : 'prometheus_metrics_pb2'
  # @@protoc_insertion_point(class_scope:io.prometheus.client.MetricFamily)
  })
_sym_db.RegisterMessage(MetricFamily)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024io.prometheus.client'
  _METRICTYPE._serialized_start=934
  _METRICTYPE._serialized_end=1011
  _LABELPAIR._serialized_start=50
  _LABELPAIR._serialized_end=90
  _GAUGE._serialized_start=92
  _GAUGE._serialized_end=114
  _COUNTER._serialized_start=116
  _COUNTER._serialized_end=140
  _QUANTILE._serialized_start=142
  _QUANTILE._serialized_end=185
  _SUMMARY._serialized_start=187
  _SUMMARY._serialized_end=288
  _UNTYPED._serialized_start=290
  _UNTYPED._serialized_end=314
  _HISTOGRAM._serialized_start=316
  _HISTOGRAM._serialized_end=415
  _BUCKET._serialized_start=417
  _BUCKET._serialized_end=472
  _METRIC._serialized_start=475
  _METRIC._serialized_end=793
  _METRICFAMILY._serialized_start=796
  _METRICFAMILY._serialized_end=932
# @@protoc_insertion_point(module_scope)
